/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CBAForm: typeof import('./src/components/CBAForm.vue')['default']
    CBAInnerForm: typeof import('./src/components/appInner/CBAInnerForm.vue')['default']
    DJForm: typeof import('./src/components/DJForm.vue')['default']
    DJInnerForm: typeof import('./src/components/appInner/DJInnerForm.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FJForm: typeof import('./src/components/FJForm.vue')['default']
    FJInnerForm: typeof import('./src/components/appInner/FJInnerForm.vue')['default']
    FormData: typeof import('./src/components/FormData.vue')['default']
    FullShow: typeof import('./src/components/FullShow.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    STForm: typeof import('./src/components/STForm.vue')['default']
    STInnerForm: typeof import('./src/components/appInner/STInnerForm.vue')['default']
    UploadFile: typeof import('./src/components/UploadFile.vue')['default']
    XJForm: typeof import('./src/components/XJForm.vue')['default']
    XJInnerForm: typeof import('./src/components/appInner/XJInnerForm.vue')['default']
    YCForm: typeof import('./src/components/YCForm.vue')['default']
    YCInnerForm: typeof import('./src/components/appInner/YCInnerForm.vue')['default']
    YJForm: typeof import('./src/components/YJForm.vue')['default']
    YJInnerForm: typeof import('./src/components/appInner/YJInnerForm.vue')['default']
    ZCForm: typeof import('./src/components/ZCForm.vue')['default']
    ZCInnerForm: typeof import('./src/components/appInner/ZCInnerForm.vue')['default']
  }
}
